### ISSUE TITLE
Deprecated codegansta/cli

### ISSUE THREAD

**Issue by bloo** [tendermint/tmsp#12]
Attempting to use `tmsp-cli` for anything gets me:

`DEPRECATED Action signature.  Must be `cli.ActionFunc`.  This is an error in the application.  Please contact the distributor of this application if this is not you.  See https://github.com/codegangsta/cli/blob/master/CHANGELOG.md#deprecated-cli-app-action-signature`

**Comment by jaekwon** [comment]
Should be fixed by 7ffd289

**Comment by tomtruitt** [comment]
Is this closed. I have similar issue in mintnet.

**Comment by ebuchman** [comment]
fixed in mintnet now too: https://github.com/tendermint/mintnet/commit/6c62b2cc572cabf0d147da695d1809f2a5858cea

**Comment by ebuchman** [comment]
tested with a fresh gopath and appears fixed. please reopen if not
