### ISSUE TITLE
gprc version2 compatibility

### ISSUE THREAD

**Issue by TheDukeVIP** [tendermint/tmsp#14]
Hello,

In order to make tmsp compatible with the latest gprc, could you please update github.com\tendermint\tmsp\types\types.pb.go:1327: grpc.SupportPackageIsVersion2 to github.com\tendermint\tmsp\types\types.pb.go:1327: undefined: grpc.SupportPackageIsVersion3

Thanks

**Comment by ebuchman** [comment]
Thanks.
