### ISSUE TITLE
Does Tendermint currently use Query or Info?

### ISSUE THREAD

**Issue by anthonymoralez** [tendermint/tmsp#24]
I can't find a place in the tendermint repo where anything calls through the TMSP AppConn to the TMSP application.

**Comment by ebuchman** [comment]
Tendermint does not currently use Query or Info. We may expose them through the RPC but currently they are just for debugging.

**Comment by ebuchman** [comment]
as of 0.8, tendermint exposes Query and Info via rpc and uses Info for a handshake with the app. Details upcoming with the release
