### ISSUE TITLE
Is a TMSP application responsible for saving its state?

### ISSUE THREAD

**Issue by anthonymoralez** [tendermint/tmsp#25]
When I:
1. Start a TMSP app
2. Start a `tendermint node`
3. `curl http://localhost:46657/broadcast_tx_sync?tx=....`
4. stop tendermint node
5. stop TMSP app
6. start TMSP app
7. start `tendermint node`
Then:
The TMSP app has no recollection of the previous application state unless it explicitly saves and loads it.

If that's the case then should it be writing this state on Commit?

**Comment by ebuchman** [comment]
Yes, that is correct. Tendermint itself knows nothing of your application's state other than the latest root hash. It is the application's responsibility to persist state to disk. Note we built http://github.com/tendermint/merkleeyes to facilitate this, its just a simple Merkle key-value store that persists to disk.

**Comment by anthonymoralez** [comment]
Merkleeyes doesn't actually persist data at this point in time. Though if I understand correctly it will at some point.

**Comment by tomtruitt** [comment]
Merkleyes just creates a merkletree tree for your chosen kV then right?

**Comment by ebuchman** [comment]
Using new BeginBlock/Info semantics (https://github.com/tendermint/tmsp/pull/29 and updates) and the tendermint handshake (https://github.com/tendermint/tendermint/pull/265), this is taken care of.

We still need to do something about merkleeyes tho!
